### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by RiskingTime** [MarkdaleMGMT/ReportingDashboard#12]
- how could we incorporate python?

**Comment by KT252005** [comment]
for website use" flask"  
from flask import Flask , requests,json, render_template 
here is an example file where simple calculator programed using python and then by using html and css 
the website is done .similar tools or technically speaking "API" is use for incorporate python.

example:
1) python script (for logic)
`def calculate(first, operation, second):
    a = first
    b = second
    r = operation
    if r == "+":
        return a + b
    elif r == "-":
        return a - b
    elif r == "*":
        return a * b
    elif r == "/":
        return a / b
    elif r == "%":
        return a % b
    else:
        return "Error: Invalid operation"





#app.py
from flask import Flask, render_template, request,json 

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/calculate', methods=['POST'])
 
def calculate_route():
    try:
        first = int(request.form['first'])
        operation = request.form['operation']
        second = int(request.form['second'])

        result = calculate(first, operation, second)

        return render_template('index.html', result=result)
    except Exception as e:
        return render_template('index.html', error=str(e))
         
        

if __name__ == '__main__':
    app.run(host="0.0.0.0",port=80)`


2) html program : 

`<!DOCTYPE html>
<html>
<head>
    <title>Calculator</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <div class="calculator">
        <h1>Simple Calculator</h1>
        <form method="POST" action="/calculate">
            <input type="number" name="first" placeholder="Enter first number" required>
            <select name="operation">
                <option value="+" selected>+</option>
                <option value="-">-</option>
                <option value="*">*</option>
                <option value="/">/</option>
                <option value="%">%</option>
            </select>
            <input type="number" name="second" placeholder="Enter second number" required>
            <button type="submit">Calculate</button>
        </form>
        <p>Result: {{ result }}</p>
        <p class="error">{{ error }}</p>
    </div>
</body>
</html>
 `
3) css style :
`/* Reset default margins and paddings */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: Arial, sans-serif;
    background-color: #f4f4f4;
    text-align: center;
}

.calculator {
    margin: 50px auto;
    background-color: #fff;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    width: 300px;
}

h1 {
    font-size: 24px;
    margin-bottom: 20px;
}

form {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
}

input[type="number"],
select {
    width: 80px;
    padding: 10px;
    margin: 5px;
    border: 1px solid #ccc;
    border-radius: 5px;
}

button {
    background-color: #3498db;
    color: white;
    border: none;
    padding: 10px 20px;
    cursor: pointer;
    border-radius: 5px;
}

button:hover {
    background-color: #2980b9;
}

p {
    font-size: 18px;
    margin-top: 20px;
}

.error {
    color: red;
    font-weight: bold;
}
`
👍 refer tu video :-
https://youtu.be/5aYpkLfkgRE?feature=shared


python usually use for data management and analysis thus u can use that way efficiently 
hope you got

**Comment by KT252005** [comment]
here you can see how to incorporate the python with other language :
https://youtu.be/5aYpkLfkgRE?feature=shared

the repository of calculator website is here https://github.com/KT252005/pythonincorporateing.git
