### ISSUE TITLE
Investment vs Benchmark Chart

### ISSUE THREAD

**Issue by RiskingTime** [MarkdaleMGMT/ReportingDashboard#8]
- create line charts comparing each individual investment returns vs benchmark returns over time
- display the numbers on dual axis so its easy to compare?
- ensure that "total returns" are displayed, which includes cashflows

**Comment by yumengwang0515** [comment]
For Canadian and US, in one chart or separated charts?
total return?

**Comment by yumengwang0515** [comment]
fixed

**Comment by yumengwang0515** [comment]
using vlookup
1. -cashflow
2. initial value negative
3. sum of cashflow
4. xirr * date diff/365
5. adding each new irr to initial value starting from 100
